-- AlterTable
ALTER TABLE "User" ADD COLUMN     "bankAccount" TEXT,
ADD COLUMN     "bankName" TEXT,
ADD COLUMN     "businessAddress" TEXT,
ADD COLUMN     "businessName" TEXT,
ADD COLUMN     "businessType" TEXT,
ADD COLUMN     "dateOfBirth" TEXT,
ADD COLUMN     "desiredStartDate" TEXT,
ADD COLUMN     "documents" JSONB[] DEFAULT ARRAY[]::JSONB[],
ADD COLUMN     "expectedRevenue" TEXT,
ADD COLUMN     "experienceDetails" TEXT,
ADD COLUMN     "initialInvestment" TEXT,
ADD COLUMN     "manageSeerToBradgyn" TEXT,
ADD COLUMN     "nationalId" TEXT,
ADD COLUMN     "ndaAccepted" BOOLEAN DEFAULT false,
ADD COLUMN     "numEmployees" TEXT,
ADD COLUMN     "numStaff" TEXT,
ADD COLUMN     "paymentMethod" TEXT,
ADD COLUMN     "phoneNumber" TEXT,
ADD COLUMN     "policyAccepted" BOOLEAN DEFAULT false,
ADD COLUMN     "preferredLocation" TEXT,
ADD COLUMN     "previousExperience" TEXT,
ADD COLUMN     "reasonForFranchise" TEXT,
ADD COLUMN     "relation" TEXT,
ADD COLUMN     "servicePackage" TEXT DEFAULT 'basic',
ADD COLUMN     "socialMedia" TEXT,
ADD COLUMN     "staffNames" TEXT,
ADD COLUMN     "termsAccepted" BOOLEAN DEFAULT false,
ADD COLUMN     "tradeLicense" TEXT,
ADD COLUMN     "yearsInOperation" TEXT;
